### ISSUE TITLE
Add warnings from Ded

### ISSUE THREAD

**Issue by derzhavin3016** [IShatrov/Quadratic-Equation-Solver#4]
It’s better to use warnings from ded

**Comment by IShatrov** [comment]
How do i use them?

**Comment by derzhavin3016** [comment]
How do you compile code now?

**Comment by IShatrov** [comment]
I press "Build and run" in codeblocks

**Comment by derzhavin3016** [comment]
You can install CodeBlocks build from ded, where they've already added

https://docs.google.com/document/d/1sMTzt2JMbPu3TrEAfFkQjuF1OrUGYZnE3Xy4c_jtnpE/edit?usp=sharing

In second paragraph

**Comment by IShatrov** [comment]
I have been using Ded`s build
