### ISSUE TITLE
Strange initialization

### ISSUE THREAD

**Issue by derzhavin3016** [IShatrov/Quadratic-Equation-Solver#9]
https://github.com/IShatrov/Quadratic-Equation-Solver/blob/de91cc7dabdc2f6792e35a5d790b5070f90f168d/quadratic_equation_solver/main.cpp#L61

I was talking about floating point type, not int
Did you compile it?

Related to #6

**Comment by IShatrov** [comment]
Yes, it worked

**Comment by derzhavin3016** [comment]
That is why you should use Ded's warnings

**Comment by derzhavin3016** [comment]
> Yes, it worked

![изображение](https://user-images.githubusercontent.com/37047102/185788249-adef2a41-b66b-4929-a03a-c7596720ec4c.png)

g++ warns about it by default
